### ISSUE TITLE
`type_cast' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by obrie** [pluginaweek/preferences#6]
**Erik Dahlstrand** opened this issue

When going from 0.4.1 to 0.4.2 I get

 @@@ ruby
.rvm/gems/ree-1.8.7-2010.01/gems/activesupport-2.3.5/lib/active_support/whiny_nil.rb:52:in `method_missing&rsquo;: undefined method`type_cast&rsquo; for nil:NilClass (NoMethodError)
.rvm/gems/ree-1.8.7-2010.01/gems/preferences-0.4.2/lib/preferences.rb:321:in `preferences&rsquo;
.rvm/gems/ree-1.8.7-2010.01/gems/activerecord-2.3.5/lib/active_record/base.rb:2197:in`inject&rsquo;
.rvm/gems/ree-1.8.7-2010.01/gems/preferences-0.4.2/lib/preferences.rb:320:in `each&rsquo;
.rvm/gems/ree-1.8.7-2010.01/gems/preferences-0.4.2/lib/preferences.rb:320:in`inject&rsquo;
.rvm/gems/ree-1.8.7-2010.01/gems/preferences-0.4.2/lib/preferences.rb:320:in `preferences&rsquo;
 @@@

when starting the web server.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13286/tickets/3)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**Erik Dahlstrand** commented

I finally found the problem. If you remove a preference from the model but don&rsquo;t remove the corresponding row in the database you get this error.
